"""
Shared constants for AppyHour MCP tools.

NAME_TO_SKU maps production matrix product names to internal SKU codes.
Consolidated from compare_matrix.py and _gen_swap_csv.py to prevent drift.
"""

NAME_TO_SKU = {
    # Accessories (AC-) — verified against Shopify product catalog
    "Apple Maple Butter Mini": "AC-APMB",
    "Artisan Crisp Apricot Pistachio Brandy": "AC-ACRISP",
    "Artisan Crisps - Tart Cherry Cranberry & Cacao Nib": "AC-TCRISP",
    "Bacon Marmalade": "AC-BACO",
    "Blackberry Balsamic Jam": "AC-BLBALS",
    "Caramelized Fig & Pear with Honey Mini Jam": "AC-CFPH",
    "Dark Chocolate Covered Almonds": "AC-DALM",
    "Dark Chocolate Covered Cranberries": "AC-DCRAN",
    "Dried Purple Mulberries": "AC-PMULB",
    "Dried Tart Cherries": "AC-DTCH",
    "Everything Flatbreads": "AC-EFLAT",
    "Fig Lemon Honey & Honey Preserves": "AC-FLH",
    "Gooseberry Elderflower Mini Jam": "AC-GBEF",
    "Hazelnuts": "AC-HAZEL",
    "Lemon Feta & Olive Mix": "AC-LFOLIVE",
    "Membrillo Quince Paste": "AC-MEMB",
    "Peach Bellini Preserves": "AC-PBLINI",
    "Piri Piri Cocktail Mix": "AC-PPCM",
    "Praline Pecans": "AC-PRPE",
    "Raspberry Hibiscus Jam": "AC-RHB",
    "Raw Honey with Comb": "AC-HON",
    "Red Pepper Jelly Mini": "AC-RPJ",
    "Rustic Bakery Organic Olive Oil & Sel Gris Flatbread Bites": "AC-RBOL",
    "Sesame Pretzel Flatbreads": "AC-PFLAT",
    "Spanish Salted Marcona Almonds": "AC-MARC",
    "Spiced Peach Bourbon Jam": "AC-SBPBJ",
    "Stone Ground Mustard for Cheese": "AC-MUSTCH",
    "Strawberry Lemon Lavendar Jam": "AC-SLL",
    "Strawberry Rhubarb Mini Jam": "AC-SRHUB",
    "Sun-Dried Turkish Figs": "AC-SDF",
    "Sweet & Smoky Almonds": "AC-SMAL",
    # Cheese (CH-) — verified against Shopify product catalog
    "Alp Blossom Floral Cheese": "CH-ALP",
    "Baked Lemon Ricotta": "CH-BLR",
    "Barista": "CH-BARI",
    "Barricato Al Pepe": "CH-BAP",
    "Beauty Vintage Sharp Cheddar": "CH-CSGOD",
    "Black Truffle Howling Hound Vintage Cheddar": "CH-CTGOD",
    "California Bay Blue": "CH-BBLUE",
    "California Clothbound Cheddar": "CH-FOWC",
    "Everything Bagel Cheese Curds": "CH-EBCC",
    "Farmstead Smoked Gouda": "CH-MSMG",
    "Fiddlehead IPA Cheddar": "CH-IPAC",
    "Fontal": "CH-FONTAL",
    "From the Cave": "TR-FTC",
    "Gruyere AOP": "CH-GAOP",
    "Honey Clover Gouda Packaged Slice": "CH-HCGU",
    "Imported Parmigiano Reggiano": "CH-IPRW",
    "KM39": "CH-KM39",
    "Leonora": "CH-LEON",
    "Los Cameros de Romero": "CH-LOSC",
    "Lou Bergier": "CH-LOU",
    "Manchego Aurora": "CH-MAU3",
    "Marinated Australian Farmstead Cheese": "CH-MAFT",
    "McCalls Grassfed Irish Porter Cheddar": "CH-MCPC",
    "Petit Garlic & Pepper Triple Cream Brie": "CH-GPBRIE",
    "Petit Triple Cream Brie": "CH-PBRIE",
    "Petit Truffle Triple Cream Brie": "CH-TTBRIE",
    "Piave Vecchio": "CH-PVEC",
    "Prairie Breeze": "CH-BRZ",
    "Shadow Blossom": "CH-SHADOW",
    "Sottocenere with Truffles": "CH-SOT",
    "The Drunken Goat Reserva": "CH-RQCAV",
    "Tipperary Brie": "CH-TIP",
    "Toma Provence": "CH-TOPR",
    "Triple Cream Brie": "CH-EBRIE",
    "Triple Creme Brie": "CH-EBRIE",
    "Ubriaco Pinot Rose": "CH-UROSE",
    "Ubriacone": "CH-UCONE",
    "Wensleydale with Mango & Ginger": "CH-WMANG",
    "Wooly Wooly Black Garlic": "CH-WWBG",
    "Wooly Wooly Diablo": "CH-WWDI",
    # Meat (MT-) — verified against Shopify product catalog
    "Applewood Smoked Speck": "MT-ASPK",
    "Capocollo": "MT-CAPO",
    "Finocchiona": "MT-SFEN",
    "Jamon Serrano": "MT-JAMS",
    "Jambon Honey & Herb": "MT-JAHH",
    "Lonza": "MT-LONZ",
    "Prosciutto": "MT-PRO",
    "Prosciutto Piccante": "MT-PP",
    "Red Wine & Garlic Sliced Salami": "MT-SLRWG",
    "Smoked Paprika Chorizo": "MT-SPAP",
    "Sopressata": "MT-SOP",
    "Sweet & Spicy Prosciutto": "MT-PSS",
    "Toscano Salame": "MT-TUSC",
    "Uncured Wagyu Braseola": "MT-BRAS",
    # Packaging (PK-)
    "Tasting Guide - Custom Box": "PK-TSTG",
    "Tasting Guide - Curated Box": "PK-TSTBL",
    "Tasting Guide - The First AppyHour": "PK-TSTBX0",
    # Trays (TR-) — verified against Shopify product catalog
    "American Artisan Board (Tray)": "TR-AAB",
    "Apres Ski (Tray)": "TR-APRSKI",
    "Dutch Golden Age (Tray)": "TR-DGG",
    "Italian Countryside (Tray)": "TR-ICTRY",
    "Rose All Day (Tray)": "TR-ROSE",
    "Traditional Tapas (Tray)": "TR-TAPAS",
}

FOOD_PREFIXES = ("CH-", "MT-", "AC-", "CEX-")
