"""
Shared constants for AppyHour MCP tools.

NAME_TO_SKU maps production matrix product names to internal SKU codes.
Source of truth: meal-type-export CSV from RMFG Translator portal.
Last synced: 2026-03-30
"""

NAME_TO_SKU: dict[str, str] = {
    # Accessories / Accompaniments (AC-)
    "Apple Maple Butter Mini": "AC-APMB",
    "Apricot with Orange & Honey Mini Jam": "AC-APOH",
    "Artisan Crisp Apricot Pistachio Brandy": "AC-ACRISP",
    "Artisan Crisps - Tart Cherry Cranberry & Cacao Nib": "AC-TCRISP",
    "Artisan Spiced Pumpkin Crisps": "AC-PCRISP",
    "Bacon Marmalade": "AC-BACO",
    "Black Mission Figs": "AC-MISS",
    "Blackberry Balsamic Jam": "AC-BLBALS",
    "Blackberry Rosemary Jam": "AC-BRJA",
    "Blueberry Thyme Jam": "AC-BLUTH",
    "Buttermilk Biscuit Crackers": "AC-CBIS",
    "Caramelized Fig & Pear with Honey Mini Jam": "AC-CFPH",
    "Castelvetrano Olives": "AC-CAOL",
    "Coconut Cashews": "AC-COCO",
    "Dark Chocolate Covered Almonds": "AC-DALM",
    "Dark Chocolate Covered Cranberries": "AC-DCRAN",
    "Dried Apricots": "AC-APR",
    "Dried Chocolate Covered Strawberries": "AC-STRAW",
    "Dried Mangoes": "AC-MANG",
    "Dried Nectarines": "AC-NECT",
    "Dried Papaya": "AC-DPAP",
    "Dried Peaches": "AC-DPEC",
    "Dried Purple Mulberries": "AC-PMULB",
    "Dried Tart Cherries": "AC-DTCH",
    "Edamame, Roasted & Salted": "AC-MAME",
    "Everything Flatbreads": "AC-EFLAT",
    "Fig & Almond Cake": "AC-FIGA",
    "Fig Lemon Honey & Honey Preserves": "AC-FLH",
    "Firehook Crackers": "AC-FHOO",
    "French Honey Balsamic Dijon Mustard": "AC-FALD",
    "French Onion Rosemary Jam Mini": "AC-FOJ",
    "French Tarragon Dijon Mustard": "AC-FALM",
    "Frescatrano Olives": "AC-FRESC",
    "Garlic Almonds": "AC-GAL",
    "Glazed Walnuts": "AC-WAL",
    "Gooseberry Elderflower Mini Jam": "AC-GBEF",
    "Hazelnuts": "AC-RHAZ",
    "Lemon Feta & Olive Mix": "AC-LFOLIVE",
    "Martins Handmade Pretzels 8oz": "AC-MPTZ8",
    "Mediterranean Olives & Herb Medley": "AC-MEDO",
    "Membrillo Quince Paste": "AC-MEMB",
    "Milk Chocolate Covered Pretzels": "AC-MCP",
    "Oh Snap Dilly Pickle Bites": "AC-DPIC",
    "Peach Bellini Preserves": "AC-PBLINI",
    "Piri Piri Cocktail Mix": "AC-PPCM",
    "Praline Pecans": "AC-PRPE",
    "Raspberry Hibiscus Jam": "AC-RHB",
    "Raspberry Mostarda Mini Jam": "AC-RSPM",
    "Raw Honey with Comb": "AC-HON",
    "Red Pepper Jelly Mini": "AC-RPJ",
    "Rustic Bakery Organic Olive Oil & Sel Gris Flatbread Bites": "AC-RBOL",
    "Rustic Bakery Organic Sesame Flatbread Bites": "AC-RBBS",
    "Rustic Bakery Organic Sourdough Rosemary Flatbread Bites": "AC-CROS",
    "Sesame Pretzel Flatbreads": "AC-PFLAT",
    "Spanish Cocktail Nut Mix": "AC-SCNM",
    "Spanish Salted Marcona Almonds": "AC-MARC",
    "Spiced Caramel Pear Preserve": "AC-SCP",
    "Spiced Peach Bourbon Jam": "AC-SBPBJ",
    "Stone Ground Mustard for Cheese": "AC-MUSTCH",
    "Strawberry Lemon Lavendar Jam": "AC-SLL",
    "Strawberry Rhubarb Mini Jam": "AC-SRHUB",
    "Sun-Dried Turkish Figs": "AC-SDF",
    "Sweet & Smoky Almonds": "AC-SMAL",
    "Tart Cherry with Cardamom & Port Mini Jam": "AC-TCP",
    "Valencian Mandarin Orange": "AC-VMOJ",
    "Wasabi Peas": "AC-WASP",
    "Whole Colossal Pistachios, Roasted & Salted": "AC-PIST",
    # Cheese (CH-)
    "24-Month Aged Parmigiano Reggiano": "CH-PARM",
    "Adironjack": "CH-AJACK",
    "Alp Blossom Floral Cheese": "CH-ALP",
    "Alpha Tolman": "CH-ALPHA",
    "Apple Cider Fromage": "CH-NMACF",
    "Artisan Cave Aged Sharp Cheddar": "CH-ACAC",
    "Artisan Cave Aged Sharp Cheddar.": "CH-V5CH",
    "Asiago": "CH-ASIAGO",
    "Baked Chocolate Ricotta": "CH-BCR",
    "Baked Lemon Ricotta": "CH-BLR",
    "Barely Buzzed - Coffee Cheese": "CH-BBCOF",
    "Barista": "CH-BARI",
    "Barricato Al Pepe": "CH-BAP",
    "Basil Pesto Gouda": "CH-PBGO",
    "Beauty Vintage Sharp Cheddar": "CH-CSGOD",
    "Black Truffle Howling Hound Vintage Cheddar": "CH-CTGOD",
    "Blueberry Lemon Thyme Goat Cheese": "CH-BLUELEM",
    "Cabot Clothbound": "CH-CCB",
    "Cabot Clothbound Cheddar": "CH-CCC",
    "Cabra al Gofio": "CH-CABR",
    "Caciotta Al Tartufo": "CH-CTUF",
    "California Bay Blue": "CH-BBLUE",
    "California Clothbound Cheddar": "CH-FOWC",
    "Campo de Montalban": "CH-CAMPO",
    "Challerhocker": "CH-CHALLER",
    "Comte 6 Months": "CH-6COM",
    "Cowboy Coffee": "CH-COWBOY",
    "Dutch Aged Gouda": "CH-AGOU",
    "Entremont Emmentaler": "CH-FEMM",
    "Everything Bagel Cheese Curds": "CH-EBCC",
    "Everything Bagel Goat Log": "CH-GEVE",
    "Farmstead Aged Gouda": "CH-FAG",
    "Farmstead English Stilton Blue Cheese": "CH-STIL",
    "Farmstead Fenugreek Gouda": "CH-FENG",
    "Farmstead Smoked Gouda": "CH-MSMG",
    "Fiddlehead IPA Cheddar": "CH-IPAC",
    "Fontal": "CH-FONTAL",
    "French Double Cream Brie": "CH-FDCB",
    "French Soft-Ripened Brie": "CH-FSRB",
    "Garlic Habanero Cheese Curds": "CH-GHCC",
    "Georgia Tomme Packaged Slice": "CH-TOMT",
    "Gruyere AOP": "CH-GAOP",
    "Gubbeen": "CH-GUUB",
    "Honey Bee Goat Gouda": "CH-HBGG",
    "Honey Clover Gouda Packaged Slice": "CH-HCGU",
    "Hornbacher Alpine Cheese": "CH-HORN",
    "Imported Emmentaler Swiss": "CH-EMSW",
    "Imported Parmigiano Reggiano": "CH-IPRW",
    "KM39": "CH-KM39",
    "Leonora": "CH-LEON",
    "Los Cameros de Romero": "CH-LOSC",
    "Lou Bergier": "CH-LOU",
    "Mahon Menorca": "CH-MAHO",
    "Manchego Aurora": "CH-MAU3",
    "Manchego Curado": "CH-MANC",
    "Maple Frais Fromage": "CH-NMMAP",
    "Marco Polo Packaged Slice": "CH-MPOLO",
    "Margot": "CH-MARGOT",
    "Marinated Australian Farmstead Cheese": "CH-MAFT",
    "McCalls Grassfed Irish Porter Cheddar": "CH-MCPC",
    "Mediterranean Style Feta": "CH-MSF",
    "Mini Harbison": "CH-HARBM",
    "Moses Reaper": "CH-MOSES",
    "Mustard Seed Swisserella": "CH-MSWISS",
    "Nettle Meadow Kunik": "CH-KUNIK",
    "Organic Grass-Fed Mozzarella": "CH-OGFM",
    "Petit Boo": "CH-PBOO",
    "Petit Camambert": "CH-CAM",
    "Petit Garlic & Pepper Triple Cream Brie": "CH-GPBRIE",
    "Petit Triple Cream Brie": "CH-PBRIE",
    "Petit Truffle Triple Cream Brie": "CH-TTBRIE",
    "Piave Vecchio": "CH-PVEC",
    "Pimento Cheese Cups": "CH-PIMO",
    "Port Salut": "CH-SPORT",
    "Pradera - Dutch Aged Gouda": "CH-PRAD",
    "Prairie Breeze": "CH-BRZ",
    "Prairie Breeze.": "CH-PRBZ",
    "Pumpkin Cider Fromage": "CH-NMPSC",
    "Queso de Murcia al Vino DOP": "CH-QCAV",
    "Raclette Livradios": "CH-RACL",
    "Regal de Bourgogne with Cranberries": "CH-LRB",
    "Romao Queso al Romero": "CH-ROMQ",
    "San Joaquin Gold": "CH-SJGO",
    "Shadow Blossom": "CH-SHADOW",
    "Sottocenere with Truffles": "CH-SOT",
    "Spanish Smoking Goat": "CH-SMG",
    "Summer Fields Gouda": "CH-SFG",
    "The Drunken Goat Reserva": "CH-RQCAV",
    "Tipperary Brie": "CH-TIP",
    "Toma Provence": "CH-TOPR",
    "TomaRashi": "CH-RASHI",
    "Triple Creme Brie": "CH-BRIE",
    "Truffle Seeker": "CH-TRUSEK",
    "Ubriaco Pinot Rose": "CH-UROSE",
    "Ubriaco al Prosecco": "CH-UBRI",
    "Ubriacone": "CH-UCONE",
    "VAT 17 Cheddar Packaged Slice": "CH-VAT",
    "Valdeon Blue": "CH-VBLUE",
    "Wensleydale with Mango & Ginger": "CH-WMANG",
    "Woodside Monet Chevre": "CH-MONET",
    "Wooly Wooly Black Garlic": "CH-WWBC",
    "Wooly Wooly Diablo": "CH-WWDI",
    # Cheese Wheels (CHW-)
    "Dragon Slayer Ale & Mustard Cheddar": "CHW-DRAG",
    # Meat (MT-)
    "Applewood Smoked Speck": "MT-ASPK",
    "Beef Bresaola": "MT-sBRES",
    "Beef Caraway Salami Chub": "MT-BCSC",
    "Berkshire Coppa": "MT-BKCO",
    "Black Pepper & Cherry Prosciutto 4oz": "MT-4JABPC",
    "Black Pepper Cherry Prosciutto": "MT-JABPC",
    "Black Pepper Summer Salami": "MT-BPSS",
    "Black Pepper Uncured Genoa Salami": "MT-GEN",
    "Capocollo": "MT-CAPO",
    "Chorizo Español": "MT-FS-SPAN",
    "Cider Brined Coppa": "MT-CBCO",
    "Coppa Italiana": "MT-FS-LONZ",
    "Classic Bistro Salami": "MT-STSB",
    "Finocchiona": "MT-SFEN",
    "Heritage Sopressata": "MT-FS-HERS",
    "Honey & Herb Prosciutto 4oz": "MT-4JAHH",
    "Jambon Honey & Herb": "MT-JAHH",
    "Jamon Iberico": "MT-IBHP",
    "Jamon Serrano": "MT-JAMS",
    "Juniper Salami Chub": "MT-JUNI",
    "Lonza": "MT-LONZ",
    "Prosciutto": "MT-PRO",
    "Prosciutto Bulk": "MT-FS-PRO",
    "Prosciutto Picante 4oz": "MT-4PP",
    "Prosciutto Piccante": "MT-PP",
    "Ramp Salami": "MT-RAMP",
    "Salame Rustico": "MT-FS-RUST",
    "Red Wine & Garlic Salami Chub": "MT-REDW",
    "Red Wine & Garlic Sliced Salami": "MT-SLRWG",
    "Salted Fennel Salami Chub": "MT-SFNL",
    "Smoked Paprika Chorizo": "MT-SPAP",
    "Sopressata": "MT-SOP",
    "Southern Chorizo": "MT-STCZ",
    "Southern Coppa": "MT-STCOP",
    "Southern Smash": "MT-SMASH",
    "Speck Italiano": "MT-FS-ITSPK",
    "Sweet & Spicy Prosciutto": "MT-PSS",
    "Sweet & Spicy Prosciutto 4oz": "MT-4PSS",
    "Toscano Salame": "MT-TUSC",
    "Uncured Wagyu Braseola": "MT-BRAS",
    # Packaging (PK-)
    "Tasting Guide - BOX0": "PK-TSTBX0",
    "Tasting Guide - Blue": "PK-TSTBL",
    "Tasting Guide - Curated Box": "PK-TSTG",
    "Tasting Guide - Custom Box": "PK-TCUST",
    "Tasting Guide - Mediterranean Escape": "PK-TMDT",
    "Tasting Guide - Orange": "PK-TSTOR",
    "Tasting Guide - The First AppyHour": "PK-FCUST",
    # Trays (TR-)
    "Alpine Apertivo": "TR-ALPAP",
    "American Artisan Board (Tray)": "TR-AAB",
    "Apres Ski (Tray)": "TR-APRES",
    "Dutch Golden Age (Tray)": "TR-DGG",
    "From the Cave": "TR-FTC",
    "From the Cave (Tray)": "TR-FTC",
    "Italian Countryside (Tray)": "TR-ICTRY",
    "Rose All Day (Tray)": "TR-ROSE",
    "Salt Fat Heat": "TR-SFH",
    "Traditional Tapas (Tray)": "TR-TAPAS",
    # Pairings (PR-)
    "Artisan Cave Aged Cheddar & Blueberry Thyme Jam": "PR-ACACBL",
    "Everything Bagel Goat Log & Blueberry Thyme Jam": "PR-GEVEBL",
    "Gruyere AOP & Blackberry Jam": "PR-GRUBLK",
    "Mahon Menorca & Caramelized Fig Jam": "PR-MAHOCFP",
    "Manchego Curado & Valencia Orange Jam": "PR-MANCOG",
    "Marco Polo & Valencia Orange Jam": "PR-MPOLOVMOJ",
    "Stilton Blue Cheese & Blueberry Thyme Jam": "PR-STIBL",
    "Triple Creme Brie & Blueberry Thyme Jam": "PR-BRIBL",
    "VAT 17 Cheddar & Blueberry Thyme Jam": "PR-VATBLUTH",
    # Extras (EX-)
    "Extra 24oz Gel Pack": "EX-ICE",
    # Aliases (alternate spellings in older matrix files)
    "Triple Cream Brie": "CH-EBRIE",
}

FOOD_PREFIXES: tuple[str, ...] = ("CH-", "MT-", "AC-", "CEX-")
