"""
Shared constants for AppyHour MCP tools.

NAME_TO_SKU maps production matrix product names to internal SKU codes.
Consolidated from compare_matrix.py and _gen_swap_csv.py to prevent drift.
"""

NAME_TO_SKU = {
    "Apple Maple Butter Mini": "AC-APMB",
    "Applewood Smoked Speck": "MT-ASPK",
    "Artisan Crisp Apricot Pistachio Brandy": "AC-ACRISP",
    "Artisan Crisps - Tart Cherry Cranberry & Cacao Nib": "AC-TCRISP",
    "Bacon Marmalade": "AC-BACO",
    "Baked Lemon Ricotta": "CH-BLR",
    "Barista": "CH-BARI",
    "Barricato Al Pepe": "CH-BAP",
    "Blackberry Balsamic Jam": "AC-BLBALS",
    "California Clothbound Cheddar": "CH-FOWC",
    "Capocollo": "MT-CAPO",
    "Caramelized Fig & Pear with Honey Mini Jam": "AC-CFPH",
    "Dark Chocolate Covered Almonds": "AC-DALM",
    "Dark Chocolate Covered Cranberries": "AC-DCRAN",
    "Dried Tart Cherries": "AC-DTCH",
    "Everything Bagel Cheese Curds": "CH-EBCC",
    "Everything Flatbreads": "AC-EFLAT",
    "Farmstead Smoked Gouda": "CH-MSMG",
    "Fiddlehead IPA Cheddar": "CH-IPAC",
    "Fig Lemon Honey & Honey Preserves": "AC-FLH",
    "Finocchiona": "MT-SFEN",
    "Fontal": "CH-FONTAL",
    "Gooseberry Elderflower Mini Jam": "AC-GBEF",
    "Hazelnuts": "AC-HAZEL",
    "Jamon Serrano": "MT-JAMS",
    "Jambon Honey & Herb": "MT-JAHH",
    "KM39": "CH-KM39",
    "Lemon Feta & Olive Mix": "AC-LFOLIVE",
    "Leonora": "CH-LEON",
    "Lonza": "MT-LONZ",
    "Los Cameros de Romero": "CH-LOSC",
    "Manchego Aurora": "CH-MAU3",
    "Marinated Australian Farmstead Cheese": "CH-MAFT",
    "McCalls Grassfed Irish Porter Cheddar": "CH-MCPC",
    "Peach Bellini Preserves": "AC-PBLINI",
    "Petit Garlic & Pepper Triple Cream Brie": "CH-GPBRIE",
    "Petit Truffle Triple Cream Brie": "CH-TTBRIE",
    "Piave Vecchio": "CH-PVEC",
    "Piri Piri Cocktail Mix": "AC-PPCM",
    "Prairie Breeze": "CH-BRZ",
    "Praline Pecans": "AC-PRPE",
    "Prosciutto": "MT-PRO",
    "Raspberry Hibiscus Jam": "AC-RHB",
    "Raw Honey with Comb": "AC-HON",
    "Red Pepper Jelly Mini": "AC-RPJ",
    "Red Wine & Garlic Sliced Salami": "MT-SLRWG",
    "Rustic Bakery Organic Olive Oil & Sel Gris Flatbread Bites": "AC-RBOL",
    "Smoked Paprika Chorizo": "MT-SPAP",
    "Sopressata": "MT-SOP",
    "Sottocenere with Truffles": "CH-SOT",
    "Spanish Salted Marcona Almonds": "AC-MARC",
    "Spiced Peach Bourbon Jam": "AC-SBPBJ",
    "Stone Ground Mustard for Cheese": "AC-MUSTCH",
    "Strawberry Lemon Lavendar Jam": "AC-SLL",
    "Strawberry Rhubarb Mini Jam": "AC-SRHUB",
    "Sun-Dried Turkish Figs": "AC-SDF",
    "Sweet & Smoky Almonds": "AC-SMAL",
    "Sweet & Spicy Prosciutto": "MT-PSS",
    "Tasting Guide - Custom Box": "PK-TSTG",
    "Tasting Guide - Curated Box": "PK-TSTBL",
    "Tasting Guide - The First AppyHour": "PK-TSTBX0",
    "Tipperary Brie": "CH-TIP",
    "Toma Provence": "CH-TOPR",
    "Toscano Salame": "MT-TUSC",
    "Ubriaco Pinot Rose": "CH-UROSE",
    "Ubriacone": "CH-UCONE",
    "Wensleydale with Mango & Ginger": "CH-WMANG",
    "Wooly Wooly Diablo": "CH-WWDI",
}

FOOD_PREFIXES = ("CH-", "MT-", "AC-", "CEX-")
